import { fileURLToPath, URL } from 'node:url';
import { resolve } from 'node:path';
import { defineConfig } from 'vite';
import { copyFile } from 'wpsjs/vite_plugins';

const root = fileURLToPath(new URL('./', import.meta.url));

export default defineConfig({
  root,
  base: './',
  plugins: [
    copyFile({ src: 'manifest.xml', dest: 'manifest.xml' }),
    copyFile({ src: 'ribbon.xml', dest: 'ribbon.xml' }),
    copyFile({ src: 'main.js', dest: 'main.js' }),
    copyFile({ src: 'js', dest: 'js' }),
    // Generated by the official wpsjs publish command; this page enables the add-in in WPS.
    copyFile({ src: 'publish.html', dest: 'publish.html' }),
  ],
  build: {
    outDir: 'dist',
    emptyOutDir: true,
    rollupOptions: { input: [resolve(root, 'index.html'), resolve(root, 'ui/taskpane.html')] },
  },
});
